description: Managed Kubernetes (EKS) on AWS Cloud
options:
  - name: cluster_name
    description: Cluster name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,32}$"
    default: 'cdev-eks'
  - name: organization
    description: Organization name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,64}$"
    default: 'my-org'
  - name: vpc_name
    description: VPC name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,64}$"
    default: 'eks-vpc'
  - name: region
    description: AWS region
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,32}$"
    default: 'us-east-1'
  - name: bucket_name
    description: AWS S3 bucket name for states
    regex: "^[a-zA-Z][a-zA-Z0-9\\-]{0,64}$"
    default: 'cdev-state'
  - name: eks_version
    description: EKS version
    default: '1.29'
help_message: |
  ###############################################################################
  # Cluster.dev project generation for AWS cloud.                                #
  # cdev console tool generator                                                 #
  ###############################################################################
  Before your begin:                                           
  1) Export environment variables (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or use profile AWS_PROFILE) for AWS auth. Details: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
  2) Create S3 bucket for Terraform states: 
        aws s3 mb s3://mybucket-name
  3) Use cdev command to plan and apply project infrastructure
